version: 0.0  
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:

    - location: scripts/install_dependecies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root